#pragma once
#define CHANGE_EFFECT "change_effect"
#define SET_EFFECT_OPTIONS "set_effect_options"
#define TICK "tick"
#define COMPLETE "complete"
#define PREPARE "prepare"
#define RUN "run"
#define STOP "stop"
#define RESET "reset"
#define PROGRESS "progress"